name: lendsqr-test-ci
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: lend_db
      DB_USER: root
      DB_PASSWORD: "root"
      DB_HOST: localhost

    steps:
      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm test
